---
AN: 'Andaman and Nicobar Islands'
AP: 'Andhra Pradesh'
AD: 'Andhra Pradesh (New)'
AR: 'Arunachal Pradesh'
AS: 'Assam'
BH: 'Bihar'
CH: 'Chandigarh'
CT: 'Chattisgarh'
DN: 'Dadra and Nagar Haveli'
DD: 'Daman and Diu'
DL: 'Delhi'
GA: 'Goa'
GJ: 'Gujarat'
HR: 'Haryana'
HP: 'Himachal Pradesh'
JK: 'Jammu and Kashmir'
JH: 'Jharkhand'
KA: 'Karnataka'
KL: 'Kerala'
LD: 'Lakshadweep Islands'
MP: 'Madhya Pradesh'
MH: 'Maharashtra'
MN: 'Manipur'
ME: 'Meghalaya'
MI: 'Mizoram'
NL: 'Nagaland'
OR: 'Odisha'
PY: 'Pondicherry'
PB: 'Punjab'
RJ: 'Rajasthan'
SK: 'Sikkim'
TN: 'Tamil Nadu'
TS: 'Telangana'
TR: 'Tripura'
UP: 'Uttar Pradesh'
UT: 'Uttarakhand'
WB: 'West Bengal'